CREATE TABLE `ridecard` (
  `rideCardId` int(11) NOT NULL AUTO_INCREMENT COMMENT '骑行会员主键',
  `accountId` int(11) NOT NULL DEFAULT '0' COMMENT '品牌id',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT '名称',
  `type` int(11) NOT NULL DEFAULT '0' COMMENT '类型',
  `createTime` datetime NOT NULL COMMENT '创建时间',
  `money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
  `timeCount` int(11) NOT NULL DEFAULT '0' COMMENT '每次骑行时长限制',
  `maxRide` int(11) NOT NULL DEFAULT '0' COMMENT '最大骑行次数',
  `userType` int(11) NOT NULL DEFAULT '0' COMMENT '使用类型',
  `enable` bit(1) DEFAULT b'1' COMMENT '是否启用',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `remark` varchar(255) DEFAULT '备注' COMMENT '备注',
  `ridecardType` int(11) NOT NULL DEFAULT '0' COMMENT '0：时长减免(默认0),1：费用减免',
  `discountDes` varchar(200) DEFAULT '' COMMENT '折扣描述',
  `price` int(11) NOT NULL DEFAULT '0' COMMENT '原本价格',
  `feeId` int(11) DEFAULT '0' COMMENT '适用车辆计费类型',
  `vaildDays` int(11) DEFAULT NULL COMMENT '有效天数',
  `vaildTime` varchar(255) DEFAULT NULL COMMENT '有效时间段',
  `validWeek` varchar(30) DEFAULT NULL COMMENT '星期(1:星期日 2:星期一 3:星期二 4:星期三 5:星期四 6:星期五) 7:星期六',
  `sort` int(2) DEFAULT '1' COMMENT '排序',
  `updateTime` datetime DEFAULT NULL COMMENT '更新时间',
  `shelfStartTime` datetime DEFAULT NULL COMMENT '上架开始时间',
  `shelfEndTime` datetime DEFAULT NULL COMMENT '上架结束时间',
  PRIMARY KEY (`rideCardId`) USING BTREE,
  KEY `rideCard_account_for_accountId` (`accountId`) USING BTREE,
  CONSTRAINT `ridecard_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `account` (`accountId`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=101369 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='骑行会员';