CREATE TABLE `user` (
  `userId` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `accountId` int(11) NOT NULL DEFAULT '0' COMMENT '平台用户id',
  `country` varchar(10) DEFAULT '86' COMMENT '国家码',
  `phone` varchar(255) NOT NULL DEFAULT '' COMMENT '手机号码',
  `sex` varchar(50) DEFAULT '0' COMMENT '性别',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `email` varchar(80) DEFAULT NULL COMMENT '邮箱',
  `depositState` int(11) NOT NULL DEFAULT '0' COMMENT '押金状态',
  `depositMoney` int(11) NOT NULL DEFAULT '0' COMMENT '押金金额',
  `money` int(11) NOT NULL DEFAULT '0' COMMENT '账户金额',
  `joinTime` datetime NOT NULL COMMENT '加入时间',
  `updateTime` datetime NOT NULL COMMENT '更新时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `imageUrl` varchar(255) DEFAULT NULL COMMENT '头像地址',
  `idNO` varchar(50) DEFAULT NULL COMMENT '身份证号码',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `nameAuth` bit(1) DEFAULT b'0' COMMENT '是否认证',
  `studentAuth` bit(1) DEFAULT b'0',
  `studentIdNo` varchar(255) DEFAULT NULL COMMENT '学生证号码',
  `depositDate` date DEFAULT NULL COMMENT '免押会员日期',
  `password` varchar(100) DEFAULT NULL COMMENT '密码',
  `rideMoney` int(11) DEFAULT NULL COMMENT '骑行卡余额',
  `ridingScore` int(11) DEFAULT '260' COMMENT '用户骑行分',
  PRIMARY KEY (`userId`) USING BTREE COMMENT '用户id',
  UNIQUE KEY `idx_user_accountId_phone_country` (`accountId`,`country`,`phone`) USING BTREE COMMENT '手机号码',
  KEY `user_index_birthday` (`birthday`) USING BTREE COMMENT '生日',
  KEY `accountId` (`accountId`,`idNO`) USING BTREE COMMENT '品牌id',
  KEY `user_index_accountId_depositState_depositMoney` (`accountId`,`depositState`,`depositMoney`) USING BTREE COMMENT '品牌押金',
  KEY `user_index_accountId_money` (`accountId`,`money`) USING BTREE COMMENT '品牌余额',
  KEY `user_index_phone` (`phone`) USING BTREE,
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `account` (`accountId`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13418847 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='一线用户';